notifications:
  slack: projetgo:jo0oI2zSh4vHUoJzBIgbWIAF#builds

language: node_js
node_js:
  - '0.10'

before_install:
  - npm -g install gulp
  - npm -g install phantomjs
  - npm install
  - gem install sass
  - gem install compass
  - gem install heroku
  - git config --global user.name "RomainJeff"
  - git config --global user.email "romain.quilliot-bergue@hetic.net"

script:
  - gulp tests

after_success:
  - rm -R app_prod
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  # Clear your current Heroku SSH keys:
  - heroku keys:clear
  # Add a new SSH key to Heroku
  - yes | heroku keys:add
  # Clone Heroku deployment repo to dist folder
  - git clone git@heroku.com:getswipe.git app_prod
  # Build
  - gulp prod
  # Commit and Push dist folder to Heroku
  - cd app_prod
  - mv index.html index.php
  - git add *
  - git commit -am "Travis CI"
  - git push origin master

env:
  global:
    secure: "f77QaLxdhus9IPVRAXKv1uOA13AHYdPjjUDmZxtzAFbfodlPvLFXYAdbzWEoRT8KUeh7+LN79ij9WjNMwQ2mR0WvVR66eKWifFEP/5PAxhtaxPgsuTwdmZ39ubzWt1ppPjfAM+UQWIJbGDyePl/sQmMi7BNKURmVsTXhozYMbng="

branches:
  only:
    - master
