notifications:
  slack: projetgo:jo0oI2zSh4vHUoJzBIgbWIAF#builds

language: node_js
node_js:
  - '0.10'

before_install:
  - npm -g install gulp
  - npm -g install phantomjs
  - npm install

script:
  - gulp tests

env:
  global:
    secure: "f77QaLxdhus9IPVRAXKv1uOA13AHYdPjjUDmZxtzAFbfodlPvLFXYAdbzWEoRT8KUeh7+LN79ij9WjNMwQ2mR0WvVR66eKWifFEP/5PAxhtaxPgsuTwdmZ39ubzWt1ppPjfAM+UQWIJbGDyePl/sQmMi7BNKURmVsTXhozYMbng="
